### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by Ashu-Shah** [JanPeter/RN-NavigationHeaderAnimation#1]
Hey @JanPeter yesterday i was searching the answer for my issue then I got your answer from [stackoverflow](https://stackoverflow.com/questions/45143026/tabview-as-sticky-header-in-react-native#). I have same problem and I have implemented your code. Still i m getting three issues.
1# 
![screenshot_2017-07-19-12-56-28](https://user-images.githubusercontent.com/12493946/28359384-698d8f98-6c8b-11e7-854e-d1fee3762843.png)

"I want full scrolling not after tab content scroll. I want be able to scroll from banner."

2#
![screenshot_2017-07-19-12-57-31](https://user-images.githubusercontent.com/12493946/28359402-7bd7c90c-6c8b-11e7-9b9a-c411d17b2bee.png)

"When i am scrolling the banner is jerking while going up side."

3# My first post is going back side while scrolling I can't see my first post.

**Comment by JanPeter** [comment]
You mean when you start scrolling, the banner and your post is moving up simultaneously? I know this is a problem. I'll try to fix that today!

**Comment by Ashu-Shah** [comment]
Yes this is the issue. And how can i scroll from banner also. Please let me know when you fixed it. Thanks in advance :).

**Comment by JanPeter** [comment]
Alright! Thanks for the quick response 👍 
Although I'm not quite sure what you mean with "scroll from banner"? Could you describe this any further?

**Comment by Ashu-Shah** [comment]
@JanPeter currently the scroll is in tab i need to scroll on stack and child tab need to scroll when tab stick at top. Now are you getting my point?

**Comment by JanPeter** [comment]
@Ashu-Shah I fixed this now and hooked up the stack navigator with the tab navigator. But I don't quite get why you want to have two scroll views in one screen? That's an anti pattern for ux, isn't it?

**Comment by Ashu-Shah** [comment]
@JanPeter first we need scroll on stack and when tab stick on top then we need to remove stack scroll and create tab scroll.

**Comment by JanPeter** [comment]
I'm sorry to disappoint you, but I'm not going to implement that, as I don't think anyone should do this. I never read about such a scroll logic in the design guidelines for iOS or Android (didn't read them in a while and not all of it, so if you find an article that proves me wrong, please comment the link for me).

But you can implement that yourself. Have a look into the [onscroll](https://facebook.github.io/react-native/docs/scrollview.html#onscroll) event at the ScrollView component and then you can disable the scrolling for another scrollview with `setNativeProps({ scrollEnabled: false })`
