### ISSUE TITLE
how to change background color of tab bar?

### ISSUE THREAD

**Issue by mayupat13** [JanPeter/RN-NavigationHeaderAnimation#3]
Hello @JanPeter  i implemented this for android, the background color of tab bar is defaultly taken in blue but i want to change that background color 
i done in this way 
```<TabView navigation={this.props.navigation} style= {{ backgroundColor: '#ff6600' }} />```
and also tried by another ways but its not working, How can i change that background color? Please help.

**Comment by JanPeter** [comment]
I'm not sure if this is up to date, but I think you'll have to define the color at the initialisation of your `TabView` like this:

```
const TabView = TabNavigator(
  {
    feed: { screen: Feed },
    info: { screen: Info },
  },
  {
    tabBarPosition: "top",
    tabBarOptions: {
      style: {
        backgroundColor: 'blue',
      },
    },
  },
);
```

I have not tried this myself, but according to https://reactnavigation.org/docs/navigators/tab it should work.
