### ISSUE TITLE
Android issue

### ISSUE THREAD

**Issue by kerimdemir** [JanPeter/RN-NavigationHeaderAnimation#5]
![videotogif_2018 05 28_17 03 05](https://user-images.githubusercontent.com/19932626/40618230-8fe93f66-6299-11e8-962a-26be94742fca.gif)

**Comment by emmx** [comment]
Could you fix this? I'm having the same issue. Duplicate of #4.

**Comment by JanPeter** [comment]
Closing in favor of #4
